# Form implementation generated from reading ui file 'KeyLogger.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KeyLogger(object):
    def setupUi(self, KeyLogger):
        KeyLogger.setObjectName("KeyLogger")
        KeyLogger.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        KeyLogger.setFont(font)
        self.centralwidget = QtWidgets.QWidget(KeyLogger)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkKeyboardClick = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkKeyboardClick.setFont(font)
        self.checkKeyboardClick.setChecked(True)
        self.checkKeyboardClick.setObjectName("checkKeyboardClick")
        self.verticalLayout.addWidget(self.checkKeyboardClick)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkMouseClick = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkMouseClick.setFont(font)
        self.checkMouseClick.setChecked(True)
        self.checkMouseClick.setObjectName("checkMouseClick")
        self.horizontalLayout_2.addWidget(self.checkMouseClick)
        self.checMouseClickCoord = QtWidgets.QCheckBox(self.groupBox)
        self.checMouseClickCoord.setChecked(True)
        self.checMouseClickCoord.setObjectName("checMouseClickCoord")
        self.horizontalLayout_2.addWidget(self.checMouseClickCoord)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkMouseRelease = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkMouseRelease.setFont(font)
        self.checkMouseRelease.setObjectName("checkMouseRelease")
        self.horizontalLayout_3.addWidget(self.checkMouseRelease)
        self.checMouseReleaseCoord = QtWidgets.QCheckBox(self.groupBox)
        self.checMouseReleaseCoord.setObjectName("checMouseReleaseCoord")
        self.horizontalLayout_3.addWidget(self.checMouseReleaseCoord)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolTray = QtWidgets.QToolButton(self.centralwidget)
        self.toolTray.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolTray.setFont(font)
        self.toolTray.setText("")
        self.toolTray.setIconSize(QtCore.QSize(40, 40))
        self.toolTray.setObjectName("toolTray")
        self.horizontalLayout.addWidget(self.toolTray)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        KeyLogger.setCentralWidget(self.centralwidget)

        self.retranslateUi(KeyLogger)
        QtCore.QMetaObject.connectSlotsByName(KeyLogger)

    def retranslateUi(self, KeyLogger):
        _translate = QtCore.QCoreApplication.translate
        KeyLogger.setWindowTitle(_translate("KeyLogger", "KEYLOGGER"))
        self.groupBox.setTitle(_translate("KeyLogger", "Settings"))
        self.checkKeyboardClick.setText(_translate("KeyLogger", "Clicking keyboard keystrokes"))
        self.checkMouseClick.setText(_translate("KeyLogger", "Clicking mouse keystrokes"))
        self.checMouseClickCoord.setText(_translate("KeyLogger", "Track coordinates"))
        self.checkMouseRelease.setText(_translate("KeyLogger", "Releasing mouse keystrokes"))
        self.checMouseReleaseCoord.setText(_translate("KeyLogger", "Track coordinates"))
        self.toolTray.setToolTip(_translate("KeyLogger", "Hide to tray"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KeyLogger = QtWidgets.QMainWindow()
    ui = Ui_KeyLogger()
    ui.setupUi(KeyLogger)
    KeyLogger.show()
    sys.exit(app.exec())
